version: "3.9"
services:
  java_app:
    container_name: java_app
    image: imgfivvy_1.0.0
    build: .
    ports:
     - 8082:8082
    environment:
     - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
     - DATABASE_USER=postgres
     - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
volumes:
  data:
    driver: local
networks:
  defauly:
    name: fivvyNetwork
